/**
 * Supabase middleware — NOT applicable for this Vite-based app.
 *
 * This file was auto-generated by a Next.js template. Since this app
 * uses Vite + Vercel Serverless Functions (not Next.js middleware),
 * this middleware is not used.
 *
 * Supabase auth session management is handled client-side via
 * utils/supabase/client.ts instead.
 *
 * Keeping this file to avoid breaking any imports, but it's effectively
 * a no-op for this architecture.
 */
